-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.client
(
    gmail character varying(20) COLLATE pg_catalog."default" NOT NULL,
    client_id integer NOT NULL,
    client_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    balance integer NOT NULL,
    CONSTRAINT client_pkey PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS public.invoice
(
    invoice_id integer NOT NULL,
    time_start character varying(5) COLLATE pg_catalog."default" NOT NULL,
    time_end character varying(5) COLLATE pg_catalog."default" NOT NULL,
    cost integer NOT NULL,
    client_id integer NOT NULL,
    policytype character varying(25) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT invoice_pkey PRIMARY KEY (invoice_id)
);

CREATE TABLE IF NOT EXISTS public.policytype
(
    policytype character varying(25) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT policytype_pkey PRIMARY KEY (policytype)
);

ALTER TABLE IF EXISTS public.invoice
    ADD CONSTRAINT i2c FOREIGN KEY (client_id)
    REFERENCES public.client (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.invoice
    ADD CONSTRAINT i2pt FOREIGN KEY (policytype)
    REFERENCES public.policytype (policytype) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;