-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.client
(
    gender character varying(20) COLLATE pg_catalog."default" NOT NULL,
    client_id integer NOT NULL,
    client_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    policy_id integer NOT NULL,
    CONSTRAINT client_pkey PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    employee_id integer NOT NULL,
    empl_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    policy_id integer NOT NULL,
    CONSTRAINT employee_pkey PRIMARY KEY (employee_id),
    CONSTRAINT uq_policy_id UNIQUE (policy_id)
);

CREATE TABLE IF NOT EXISTS public.insuramce_company
(
    name character(24) COLLATE pg_catalog."default" NOT NULL,
    address character varying(34) COLLATE pg_catalog."default" NOT NULL,
    phone integer NOT NULL,
    CONSTRAINT insuramce_company_pkey PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public.insurance_policy
(
    client_name character varying(23) COLLATE pg_catalog."default" NOT NULL,
    empl_name character varying(53) COLLATE pg_catalog."default" NOT NULL,
    policy_type character varying(65) COLLATE pg_catalog."default" NOT NULL,
    policy_id integer NOT NULL,
    client_id integer NOT NULL,
    employee_id integer NOT NULL,
    CONSTRAINT insurance_policy_pkey PRIMARY KEY (policy_id)
);

CREATE TABLE IF NOT EXISTS public.work
(
    employee_id integer NOT NULL,
    name character(1) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT work_pkey PRIMARY KEY (employee_id, name)
);

ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT fwsfs FOREIGN KEY (policy_id)
    REFERENCES public.insurance_policy (policy_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.insurance_policy
    ADD CONSTRAINT ip2c FOREIGN KEY (client_id)
    REFERENCES public.client (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.work
    ADD CONSTRAINT e2ic FOREIGN KEY (employee_id)
    REFERENCES public.employee (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.work
    ADD CONSTRAINT ic2e FOREIGN KEY (name)
    REFERENCES public.insuramce_company (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;